trigger: none

pool:
  name: Default

steps:
  - checkout: self

  - powershell: |
      Write-Host "Current Directory:"
      Get-Location

      Write-Host "Listing files:"
      Get-ChildItem -Recurse

      & "$(Build.SourcesDirectory)\scripts\deploy.ps1"
    displayName: "Deploy to Windows Laptop"
