trigger: none

pool:
  name: Default

workspace:
  clean: all

steps:
  - checkout: self
    clean: true

  - powershell: |
      Write-Host "Listing scripts folder..."
      Get-ChildItem "$(Build.SourcesDirectory)\scripts"

      & "$(Build.SourcesDirectory)\scripts\deploy.ps1"
    displayName: "Deploy to Windows Laptop"
